### ISSUE TITLE
Multiple databases

### ISSUE THREAD

**Issue by froatsnook** [carbureted/react-native-pouchdb#2]
I am having a problem when using multiple databases.  The databases lock up (without any errors) and my promises just don't resolve/reject.

``` javascript
var People = new PouchDB("People");
var Places = new PouchDB("Places");
```

I think I can workaround by adding an extra "db" field or something.  Maybe it's easier that way anyway with the syncing.  But is anyone using multiple databases?  (@carbureted, @jonathonklem)

**Comment by carbureted** [comment]
I haven't used multiple databases, but that sounds pretty annoying. I'll take a look at it when I have time, not 100% sure when that will be.

**Comment by carbureted** [comment]
If this issue is mission critical for you, and you don't necessarily need the pouchdb ecosystem itself, you could check this out - https://github.com/couchbaselabs/react-native-couchbase-lite. It wasn't around when I initially started playing with this, and I haven't used it, but it could be a more reliable/better supported way to sync with couchdb.

**Comment by froatsnook** [comment]
Thanks for the suggestion.  Unfortunately I don't think react-native-couchbase-lite will work for me since I'm already too invested in pouchdb.

More info on this [here](https://github.com/nolanlawson/pouchdb-find/issues/174).  I'll close this issue because I don't think it has to do with react-native-pouchdb, but rather probably react-native-sqlite-storage.

Thanks for your help :).

**Comment by felarof99** [comment]
What do you guys think about using React Native's asyncstorage adapter? (instead of websql)

https://github.com/stockulus/pouchdb-asyncstorage-down
